-- mail hub v2.0.0, schema 1: the v1 hub's records (orgs, messages,
-- attachments) on PostgreSQL, with v1's meaning kept column for column.
-- Later schemas only ADD tables and nullable columns beside these.
--
-- Times: the hub's own clock is timestamptz at millisecond precision and is
-- rendered as v1 rendered it (2026-10-08T12:00:00.123Z). What a CLIENT claims
-- (sent_at, a receipt's `at`) is kept verbatim as text, exactly as v1 did.
-- Addresses and ids are compared bytewise (COLLATE "C"), as SQLite did.

CREATE TABLE hub_meta (
  k text COLLATE "C" PRIMARY KEY,
  v jsonb NOT NULL
);

-- v1 `orgs`: one row per registered address. The hub stores no secret, only
-- sha256(secret) hex, compared in full.
CREATE TABLE identities (
  slug          text COLLATE "C" PRIMARY KEY,
  fingerprint   text NOT NULL,
  org_name      text NOT NULL DEFAULT '',
  username      text NOT NULL DEFAULT '',
  blurb         text NOT NULL DEFAULT '',
  kind          text NOT NULL DEFAULT 'org',      -- org | chat
  registered_at timestamptz NOT NULL,
  last_seen     timestamptz
);
CREATE INDEX identities_silence ON identities ((COALESCE(last_seen, registered_at)));

CREATE TABLE messages (
  -- v1's SQLite rowid: the tie-break after received_at in every ordering,
  -- and the operator view's keyset cursor `n`
  n               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id              text COLLATE "C" NOT NULL UNIQUE,  -- client-minted: idempotent send
  from_slug       text COLLATE "C" NOT NULL,
  to_slug         text COLLATE "C" NOT NULL,
  body            text NOT NULL,
  kind            text,
  thread_id       text,                              -- reserved, passed through
  sent_at         text,                              -- the sender's claim, display only
  received_at     timestamptz NOT NULL,              -- hub clock: the ordering authority
  state           text NOT NULL DEFAULT 'queued' CHECK (state IN ('queued', 'fetched')),
  fetched_at      timestamptz,
  delivered_at    text,
  read_at         text,
  receipts_pushed boolean NOT NULL DEFAULT true,     -- false = the sender is owed an update
  attachments     jsonb NOT NULL DEFAULT '[]'        -- [{id, name, bytes}] as sent
);
CREATE INDEX messages_queue ON messages (to_slug, received_at, n) WHERE state = 'queued';
CREATE INDEX messages_owed ON messages (from_slug, n) WHERE NOT receipts_pushed;
CREATE INDEX messages_order ON messages (received_at, n);
CREATE INDEX messages_from ON messages (from_slug, received_at, n);
CREATE INDEX messages_to ON messages (to_slug, received_at, n);

-- metadata only: the bytes are files under <HUB_DATA>/blobs/<id>
CREATE TABLE attachments (
  id         text COLLATE "C" PRIMARY KEY,
  owner_slug text COLLATE "C" NOT NULL,
  name       text NOT NULL,
  bytes      bigint NOT NULL,
  created_at timestamptz NOT NULL,
  message_id text COLLATE "C"                        -- NULL until a send binds it
);
CREATE INDEX attachments_created ON attachments (created_at);
